version: "3"

services:

  produto:
    build: ./api-produto
    entrypoint: ./.docker/entrypoint.sh
    container_name: hubees-express-produto
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./api-produto:/home/node/produto
    depends_on: 
      - rabbitmq
      - dbpostgres

  extrato:
    build: ./api-extrato
    entrypoint: ./.docker/entrypoint.sh
    container_name: hubees-express-extrato
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3000
    volumes:
      - ./api-extrato:/home/node/extrato
    depends_on: 
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: hubees-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  dbpostgres:
    image: postgres
    container_name: hubees-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hubees